In [39]:
import pandas as pd
import numpy as np

In [40]:
obj=pd.Series([1,2,3,4,5])

In [41]:
obj

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [42]:
obj.values

array([1, 2, 3, 4, 5])

In [43]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [58]:
df = pd.DataFrame([[1,2],[3,4],[5,6],[7,8],[9,10]],
                    index=['A','B','C','D','E'],
                    columns=['x','y'])

In [59]:
df

   x   y
A  1   2
B  3   4
C  5   6
D  7   8
E  9  10

In [60]:
np.exp(df)

             x             y
A     2.718282      7.389056
B    20.085537     54.598150
C   148.413159    403.428793
D  1096.633158   2980.957987
E  8103.083928  22026.465795

In [62]:
'B' in df

False